### ISSUE TITLE
Typo in prerequisite specification (URI::File instead URI::file)

### ISSUE THREAD

**Issue by eserte** [draegtun/PerlX-QuoteOperator-URL#2]
build_requires specifies URI::File, but probably you meant URI::file. CPAN.pm shows this message while trying to install the module:

```
---- DRAEGTUN/PerlX-QuoteOperator-URL-1.01.tar.gz ----
    URI::File [build_requires]
    PerlX::QuoteOperator [requires]
Running install for module 'URI::File'

  The module URI::File isn't available on CPAN.

  Either the module has not yet been uploaded to CPAN, or it is
  temporary unavailable. Please contact the author to find out
  more about the status. Try 'i URI::File'.
```

**Comment by draegtun** [comment]
Many thanks for spotting this @eserte

This typo unfortunately sneaked in with PR1 - https://github.com/draegtun/PerlX-QuoteOperator-URL/pull/1   :(

Fixed and uploaded to CPAN - https://metacpan.org/release/DRAEGTUN/PerlX-QuoteOperator-URL-1.02

kind regards, Barry
